// Shared source of truth for all team data.
// Update contact emails/phones here once confirmed — overview + team pages read from this.
export const TEAMS = [
  {
    id: 'herren1',
    slug: 'Team-Herren-1.dc.html',
    tag: '[ TEAM H1 ]',
    name: 'HERREN 1',
    short: 'Herren 1',
    level: 'LEISTUNG · LIGA',
    league: 'Herren · Ligabetrieb',
    bg: '#D8232A',
    desc: 'Unser ambitioniertes Aushängeschild im Herrenbereich. Hier wird zielstrebig auf Punkte und Aufstieg hingearbeitet — mit intensivem Training und echtem Wettkampfgeist.',
    chips: ['Wettkampf', 'Ligabetrieb', 'Athletik'],
    training: 'Termine folgen',
    contactName: 'Dominic Lassig',
    contactEmail: '',
    contactPhone: '',
    instagram: 'bbtburschen',
    instaIsClub: false,
  },
  {
    id: 'herren2',
    slug: 'Team-Herren-2.dc.html',
    tag: '[ TEAM H2 ]',
    name: 'HERREN 2',
    short: 'Herren 2',
    level: 'AUFBAU · LIGA',
    league: 'Herren · Ligabetrieb',
    bg: '#15110F',
    desc: 'Die ideale Mannschaft, um sich spielerisch weiterzuentwickeln. Ehrgeizig, aber mit Raum zum Reinwachsen — perfekt für den Sprung Richtung Leistungsbereich.',
    chips: ['Entwicklung', 'Ligabetrieb', 'Teamspirit'],
    training: 'Termine folgen',
    contactName: 'Noah Fäßler',
    contactEmail: '',
    contactPhone: '',
    instagram: 'bbt_paderborn2',
    instaIsClub: false,
  },
  {
    id: 'damen',
    slug: 'Team-Damen.dc.html',
    tag: '[ TEAM D1 ]',
    name: 'DAMEN',
    short: 'Damen',
    level: 'LEISTUNG · LIGA',
    league: 'Damen · Ligabetrieb',
    bg: '#D8232A',
    desc: 'Starkes, eingespieltes Damenteam mit klaren Zielen. Technik, Taktik und Zusammenhalt stehen im Mittelpunkt — auf und neben dem Feld.',
    chips: ['Wettkampf', 'Ligabetrieb', 'Technik'],
    training: 'Termine folgen',
    contactName: 'Nathalie Borchert',
    contactEmail: '',
    contactPhone: '',
    instagram: 'bbtchics',
    instaIsClub: false,
  },
  {
    id: 'hobbyleistung',
    slug: 'Team-Hobby-Leistung.dc.html',
    tag: '[ TEAM HL ]',
    name: 'HOBBY LEISTUNG',
    short: 'Hobby Leistung',
    level: 'AMBITIONIERT · TRAINING',
    league: 'Trainingsbetrieb · ohne festen Ligadruck',
    bg: '#15110F',
    desc: 'Für alle, die es ernst meinen, aber ohne festen Ligadruck spielen wollen. Anspruchsvolles Training, hohes Niveau und jede Menge Spaß am Spiel.',
    chips: ['Anspruchsvoll', 'Mixed möglich', 'Regelmäßig'],
    training: 'Termine folgen',
    contactName: 'Allegra Joelle Vogel',
    contactEmail: '',
    contactPhone: '',
    instagram: 'beachbangtheorypaderborn',
    instaIsClub: true,
  },
  {
    id: 'hobby',
    slug: 'Team-Hobby.dc.html',
    tag: '[ TEAM HB ]',
    name: 'HOBBY',
    short: 'Hobby',
    level: 'SPASS · MIXED',
    league: 'Trainingsbetrieb · Mixed',
    bg: '#B01419',
    desc: 'Der lockere Einstieg in den Vereinssport. Bewegung, Gemeinschaft und Volleyball ohne Leistungsdruck — Neulinge sind hier ausdrücklich willkommen.',
    chips: ['Einsteiger willkommen', 'Mixed', 'Locker'],
    training: 'Termine folgen',
    contactName: 'Vito Antonino',
    contactEmail: '',
    contactPhone: '',
    instagram: 'beachbangtheorypaderborn',
    instaIsClub: true,
  },
];

export function teamById(id) {
  return TEAMS.find((t) => t.id === id) || null;
}
